FamilySite.UI.MVC/Controllers/LessonsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using FamilySite.DATA.EF;
using Microsoft.AspNet.Identity;//User.Identity.GetUserId()
using System.Net.Mail;

namespace FamilySite.UI.MVC.Controllers
{
    public class LessonsController : Controller
    {
        private FamilySiteEntities db = new FamilySiteEntities();

        // GET: Lessons
        public ActionResult Index()
        {
            var lessons = db.Lessons.Include(l => l.Cours);
            return View(lessons.ToList());
        }

        // GET: Lessons/Details/5
        public ActionResult Details(int? id)//id = lesson id
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Lesson lesson = db.Lessons.Find(id);
            if (lesson == null)
            {
                return HttpNotFound();
            }

            #region lesson view record creation (coder: hjkang)
            string currentUserID = User.Identity.GetUserId();
            if (currentUserID != null)
            {
                LessonView lessonview = new LessonView();

                lessonview.LessonID = lesson.LessonID;
                lessonview.UserID = currentUserID;
                lessonview.DateViewed = DateTime.Now;
                db.LessonViews.Add(lessonview);
                db.SaveChanges();

                #endregion

                #region record creation of course completion  (coder: hjkang)
                // if # of lessons in the course == # of lesson views by the user, then the course of the user is completed.

                //# of lessons in the course
                var nbrLessons = db.Lessons.Where(x => x.CourseID == lesson.CourseID).Count();

                //# of lesson views for the course 
                var nbrLessonsViewed = 0;
                var lessonViews = db.LessonViews.Where(x => (x.Lesson.CourseID == lesson.CourseID) && (x.UserID == currentUserID));


                var fc = lessonViews.OrderBy(x => x.LessonID).ToList();


                if (fc.Count() == 1)
                {
                    nbrLessonsViewed = 1;
                }
                else
                {
                    for (int i = 0; i < (fc.Count() - 1); i++)
                    {
                        var elementA = fc.ElementAt(i);
                        var elementB = fc.ElementAt(i + 1);
                        if (elementA.LessonID != elementB.LessonID)
                        {
                            nbrLessonsViewed++;
                        }
                    }
                    nbrLessonsViewed += 1;
                }


                if (nbrLessonsViewed == nbrLessons)
                {
                    CourseCompletion courseComplete = new CourseCompletion();
                    courseComplete.UserID = currentUserID;
                    courseComplete.CourseID = lesson.CourseID;
                    courseComplete.DateCompleted = DateTime.Now;

                    db.CourseCompletions.Add(courseComplete);
                    db.SaveChanges();

                    //send email to the parent(a manager) to notify when a child completes a course
                    var user = db.UserDetails.Where(u => u.UserID == currentUserID).SingleOrDefault();


                    string body = string.Format($"{user.FirstName}"
                        + " has completed " + $"the course of {lesson.Cours.CourseName}" + $" on {DateTime.Now}.");

                    MailMessage msg = new MailMessage(
                        "no-reply@hjkangweb.com",
                        "speedkhj@gmail.com",
                        "Your child completed a course.",
                        body);

                    msg.IsBodyHtml = true;
                    msg.CC.Add("postmaster@hjkangweb.com");

                    SmtpClient client = new SmtpClient("mail.hjkangweb.com");

                    client.Credentials = new NetworkCredential("no-reply@hjkangweb.com", "kang1226@@");
                    client.EnableSsl = false;
                    client.Port = 25;

                    using (client)
                    {
                        try
                        {
                            client.Send(msg);
                        }
                        catch
                        {
                            ViewBag.ErrorMessage = "There was an error sending complete notification. \n" + "Please notify your parent you have completed the course.";
                        }
                    }

                }

                #endregion
            }

            return View(lesson);
        }

        [Authorize(Roles = "Admin")]
        // GET: Lessons/Create
        public ActionResult Create()
        {
            ViewBag.CourseID = new SelectList(db.Courses1, "CourseID", "CourseName");
            return View();
        }

        [Authorize(Roles = "Admin")]
        // POST: Lessons/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "LessonID,LessonTitle,CourseID,Introduction,VideoURL,PdfFileName,IsActive,ReservationLimit")] Lesson lesson, HttpPostedFileBase pdfFile)
        {
            if (ModelState.IsValid)
            {
                string lessonMaterial = "noFile.jpg";
                if (pdfFile != null)
                {
                    lessonMaterial = pdfFile.FileName;
                    string ext = lessonMaterial.Substring(lessonMaterial.LastIndexOf("."));
                    //.pdf, .doc, .docx, .html, .xlsx, .jpg
                    string[] goodExts = new string[] { ".pdf", ".doc", ".docx", ".html", ".xlsx", ".xls", ".jpg", ".png", ".gif", ".jpeg" };
                    if (goodExts.Contains(ext.ToLower()))
                    {
                        lessonMaterial = Guid.NewGuid() + lessonMaterial;
                        pdfFile.SaveAs(Server.MapPath("~/Content/textfiles/Lessons/" + lessonMaterial));
                    }
                    else
                    {
                        lessonMaterial = "noFile.jpg";
                    }
                }
                lesson.PdfFileName = lessonMaterial;

                db.Lessons.Add(lesson);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.CourseID = new SelectList(db.Courses1, "CourseID", "CourseName", lesson.CourseID);
            return View(lesson);
        }

        [Authorize(Roles = "Admin")]
        // GET: Lessons/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Lesson lesson = db.Lessons.Find(id);
            if (lesson == null)
            {
                return HttpNotFound();
            }
            ViewBag.CourseID = new SelectList(db.Courses1, "CourseID", "CourseName", lesson.CourseID);
            return View(lesson);
        }

        [Authorize(Roles = "Admin")]
        // POST: Lessons/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "LessonID,LessonTitle,CourseID,Introduction,VideoURL,PdfFileName,IsActive,ReservationLimit")] Lesson lesson, HttpPostedFileBase pdfFile)
        {
            if (ModelState.IsValid)
            {
                string lessonMaterial = "noFile.jpg";
                if (pdfFile != null)
                {
                    lessonMaterial = pdfFile.FileName;
                    string ext = lessonMaterial.Substring(lessonMaterial.LastIndexOf("."));
                    //.pdf, .doc, .docx, .html, .xlsx, .jpg
                    string[] goodExts = new string[] { ".pdf", ".doc", ".docx", ".html", ".xlsx", ".xls", ".jpg", ".png", ".gif", ".jpeg" };
                    if (goodExts.Contains(ext.ToLower()))
                    {
                        lessonMaterial = Guid.NewGuid() + lessonMaterial;
                        pdfFile.SaveAs(Server.MapPath("~/Content/textfiles/Lessons/" + lessonMaterial));
                    }
                    else
                    {
                        lessonMaterial = "noFile.jpg";
                    }
                }
                lesson.PdfFileName = lessonMaterial;

                db.Entry(lesson).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.CourseID = new SelectList(db.Courses1, "CourseID", "CourseName", lesson.CourseID);
            return View(lesson);
        }

        [Authorize(Roles = "Admin")]
        // GET: Lessons/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Lesson lesson = db.Lessons.Find(id);
            if (lesson == null)
            {
                return HttpNotFound();
            }
            //Handle any delete that would orphon an connected record
            if (lesson.Reservations.Count > 0 || lesson.LessonViews.Count > 0)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            return View(lesson);
        }

        [Authorize(Roles = "Admin")]
        // POST: Lessons/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]

FamilySite.UI.MVC/Views/Lessons/Create.cshtml
@model FamilySite.DATA.EF.Lesson

@{
    ViewBag.Title = "Add New Lesson";
}
<div id="family-wrapper">
    <h3>@ViewBag.Title</h3>
    <hr />

    @using (Html.BeginForm("Create", "Lessons", FormMethod.Post, new { @enctype = "multipart/form-data" }))
    {
        @Html.AntiForgeryToken()

        <div class="form-horizontal">

            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            <div class="form-group">
                @Html.LabelFor(model => model.LessonTitle, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.LessonTitle, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.LessonTitle, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.CourseID, "Course", htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.DropDownList("CourseID", null, htmlAttributes: new { @class = "form-control" })
                    @Html.ValidationMessageFor(model => model.CourseID, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.Introduction, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Introduction, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Introduction, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.VideoURL, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.VideoURL, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.VideoURL, "", new { @class = "text-danger" })
                </div>
            </div>


            <div class="form-group">
                @Html.Label("Lesson material", htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    <input type="file" name="pdfFile" />
                </div>
            </div>


            <div class="form-group">
                @Html.LabelFor(model => model.IsActive, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    <div class="checkbox">
                        @Html.EditorFor(model => model.IsActive)
                        @Html.ValidationMessageFor(model => model.IsActive, "", new { @class = "text-danger" })
                    </div>
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.ReservationLimit, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.ReservationLimit, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.ReservationLimit, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="Create" class="btn btn-primary" />|
                    @Html.ActionLink("Cancel", "Index", null, new { @class = "btn btn-danger" })
                </div>
            </div>
        </div>
    }
</div>


@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

FamilySite.UI.MVC/Views/Lessons/Delete.cshtml
@model FamilySite.DATA.EF.Lesson

@{
    ViewBag.Title = "Delete " + Model.LessonTitle;
}
<div id="family-wrapper">
    <h2>@ViewBag.Title</h2>
    <hr />

    <h3 style="display:inline-block">Are you sure you want to delete <span class="myWarning">@Model.LessonTitle</span>?</h3>
    <div style="display:inline-block">

        @using (Html.BeginForm())
        {
            @Html.AntiForgeryToken()

            <div class="form-actions no-color" style="display:inline-block">
                <input type="submit" value="Yes" class="btn btn-primary" />|
                @Html.ActionLink("No", "Index", null, new { @class = "btn btn-danger" })
            </div>
        }
    </div>
</div>

FamilySite.UI.MVC/Views/Lessons/Details.cshtml
@model FamilySite.DATA.EF.Lesson

@{
    ViewBag.Title = Model.LessonTitle + " Details";
}
<div id="family-wrapper">
<h3>@ViewBag.Title</h3>
<hr />
<div>

    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.LessonTitle)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.LessonTitle)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Introduction)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Introduction)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.VideoURL)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.VideoURL)


            <iframe width="789" height="444" src="https://www.youtube.com/embed/iIb_BY4xBdI" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>



        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.PdfFileName)
        </dt>

        <dd>
            @if (Model.PdfFileName == "noFile.jpg")
            {
                <span>No pdf</span>
            }
            else
            {
                <a href="~/Content/textfiles/Lessons/@Model.PdfFileName" target="_blank">
                    @Model.PdfFileName.Substring(30)
                </a>
            }
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.IsActive)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.IsActive)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ReservationLimit)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ReservationLimit)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Cours.CourseName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Cours.CourseName)
        </dd>

    </dl>
</div>

<div>
    @if (User.IsInRole("Admin"))
    {
        @Html.ActionLink("Edit", "Edit", new { id = Model.LessonID }) @:|
    }
    @Html.ActionLink("Back to List", "Index")
</div>
</div>

FamilySite.UI.MVC/Views/Lessons/Edit.cshtml
@model FamilySite.DATA.EF.Lesson

@{
    ViewBag.Title = "Edit " + Model.LessonTitle;
}
<div id="family-wrapper">
<h3>@ViewBag.Title</h3>
<hr />

@using (Html.BeginForm("Edit", "Lessons", FormMethod.Post, new { @enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">


        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.LessonID)

        <div class="form-group">
            @Html.LabelFor(model => model.LessonTitle, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.LessonTitle, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.LessonTitle, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.CourseID, "CourseID", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("CourseID", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.CourseID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Introduction, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Introduction, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Introduction, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.VideoURL, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.VideoURL, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.VideoURL, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.PdfFileName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @if (Model.PdfFileName == "noFile.jpg")
                {
                    <span>No pdf</span>
                }
                else
                {
                    @Model.PdfFileName.Substring(36)
                }
            </div>
            <div class="col-md-offset-2  col-md-10">
                <input type="file" name="pdfFile" />
            </div>
        </div>



        <div class="form-group">
            @Html.LabelFor(model => model.IsActive, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.EditorFor(model => model.IsActive)
                    @Html.ValidationMessageFor(model => model.IsActive, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ReservationLimit, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ReservationLimit, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ReservationLimit, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-primary" />|
                @Html.ActionLink("Cancel", "Index", null, new { @class = "btn btn-danger" })
            </div>
        </div>
    </div>
}
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

FamilySite.UI.MVC/Views/Lessons/Index.cshtml
@model IEnumerable<FamilySite.DATA.EF.Lesson>

@{
    ViewBag.Title = "Lessons";
}
<div id="family-wrapper">
    <h3>@ViewBag.Title</h3>

    @if (User.IsInRole("Admin"))
    {
        <p>
            @Html.ActionLink("Add New Lesson", "Create")
        </p>
    }

    <table class="table">
        <thead>
            <tr>
                <th>
                    @Html.DisplayNameFor(model => model.Cours.CourseName)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.LessonTitle)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Introduction)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.VideoURL)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.PdfFileName)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.IsActive)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.ReservationLimit)
                </th>
                @if (User.Identity.IsAuthenticated)
            {
                    <th> Reservation</th>
                }

                @if (User.IsInRole("Admin"))
            {
                    <th></th>
                }
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model)
            {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.Cours.CourseName)
                    </td>
                    <td>
                        @Html.ActionLink(item.LessonTitle, "Details", new { id = item.LessonID })
                        @*@Html.DisplayFor(modelItem => item.LessonTitle)*@
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Introduction)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.VideoURL)
                    </td>
                    <td>
                        @if (item.PdfFileName == "noFile.jpg")
                        {
                            <span>No pdf</span>
                        }
                        else
                        {
                            <a href="~/Content/textfiles/Lessons/@item.PdfFileName" target="_blank">
                                @item.PdfFileName.Substring(36)
                            </a>
                        }
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.IsActive)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.ReservationLimit)
                    </td>

                    @if (User.Identity.IsAuthenticated)
                {
                        <td>
                            <a href="@Url.Action("Create", "Reservations", new { id = item.LessonID })">Reserve</a>
                        </td>
                    }


                    @if (User.IsInRole("Admin"))
                {
                        <td>
                            @Html.ActionLink("Edit", "Edit", new { id = item.LessonID }) |
                            @*@Html.ActionLink("Details", "Details", new { id=item.LessonID }) |*@

                            @if (item.LessonViews.Count == 0 && item.Reservations.Count ==0)
                            {
                                @Html.ActionLink("Delete", "Delete", new { id = item.LessonID })
                            }
                            else
                            {
                                <span class="myWarning">IN USE</span>
                            }

                        </td>
                    }

                </tr>
            }
        </tbody>
    </table>
</div>
        @*@section scripts{
                <script>
                    $(document).ready(function () {
                        $('.table').DataTable();
                    });
                </script>
            }*@