FamilySite.UI.MVC/Controllers/ReservationsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using FamilySite.DATA.EF;
using Microsoft.AspNet.Identity;

namespace FamilySite.UI.MVC.Controllers
{
    [Authorize]
    public class ReservationsController : Controller
    {
        private FamilySiteEntities db = new FamilySiteEntities();

        // GET: Reservations
        public ActionResult Index(string filter)
        {
            //if a user is "Admin" or "Parent", it can see all reservations of all members.
            //Other users can see only their records.
            if (User.IsInRole("Admin") || User.IsInRole("Parent"))
            {
                var reservations = db.Reservations.Include(r => r.UserDetail).Include(r => r.Lesson);
                return View(reservations.ToList());
            }
            else
            {
                string currentUserID = User.Identity.GetUserId();
                var reservations = db.Reservations.Include(r => r.UserDetail).Include(r => r.Lesson).Where(x => x.UserID == currentUserID);
                return View(reservations.ToList());
            }

        }

        // GET: Reservations/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Reservation reservation = db.Reservations.Find(id);
            if (reservation == null)
            {
                return HttpNotFound();
            }                        
            return View(reservation);
        }

      
        // GET: Reservations/Create
        public ActionResult Create(int? id, int? filter)
        {
            //original create()
            //ViewBag.LessonID = new SelectList(db.Lessons, "LessonID", "LessonTitle");
            //ViewBag.CourseID = new SelectList(db.Courses1, "CourseID", "CourseName");

            //if a course is selected, only lessons of the course are displayed. (hjkang)
            ViewBag.LessonID = new SelectList(db.Lessons, "LessonID", "LessonTitle");

            var coursesWithLessons = db.Courses1.Include(c => c.Lessons).Where(c => c.Lessons.Count > 0);

            ViewBag.filter = new SelectList(coursesWithLessons, "CourseID", "CourseName");

            if (filter !=null)
            {
                var lessons = db.Lessons.Where(l => l.CourseID == filter);
                if (lessons == null)
                {
                    ViewBag.LessonID = null;
                }
                else
                {
                    ViewBag.LessonID = new SelectList(lessons, "LessonID", "LessonTitle");
                 
                }

            }

            // hjkang: when a user makes a reservation on a lesson in lesson index with a lesson id.
            // it only shows the lesson connected to the lesson id from the lesson index.
            if (id != null)
            {
                var lesson = db.Lessons.Where(l => l.LessonID == id);

                ViewBag.LessonID = new SelectList(lesson, "LessonID", "LessonTitle");

                var course = lesson.SingleOrDefault().CourseID;
                //In order to get courseID of lesson, I wrote below code. It needs to be simplified without foreach. (hjkang)
                //var course = 0;
                //foreach (var x in lesson)
                //{
                //    course = x.CourseID;
                //}
                ViewBag.filter = new SelectList(db.Courses1.Where(c => c.CourseID == course), "CourseID", "CourseName",course);
            }
            //end hjkang's reservation from lesson index

            // Users is displayed differently according to a role. (hjkang)
            string currentUserID = User.Identity.GetUserId();
            ViewBag.UserID = new SelectList(db.UserDetails.Where(u => u.UserID == currentUserID), "UserID", "FirstName");
           
            if (User.IsInRole("Admin")||User.IsInRole("Parent"))
            {
                ViewBag.UserID = new SelectList(db.UserDetails, "UserID", "FirstName");
            }
            //end of diplaying differently according to a role

            return View();
        }


        // POST: Reservations/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ReservationID,ReservationDate,UserID,LessonID")] Reservation reservation)
        {
            if (ModelState.IsValid)
            {
                db.Reservations.Add(reservation);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.UserID = new SelectList(db.UserDetails, "UserID", "FirstName", reservation.UserID);
            ViewBag.LessonID = new SelectList(db.Lessons, "LessonID", "LessonTitle", reservation.LessonID);
            return View(reservation);
        }


        // GET: Reservations/Edit/5
        public ActionResult Edit(int? id, int? filter)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Reservation reservation = db.Reservations.Find(id);
            if (reservation == null)
            {
                return HttpNotFound();
            }

            ViewBag.UserID = new SelectList(db.UserDetails.Where(u => u.UserID == reservation.UserID), "UserID", "FirstName"); //, reservation.UserID);

            if (User.IsInRole("Admin") || User.IsInRole("Parent"))
            {
                ViewBag.UserID = new SelectList(db.UserDetails, "UserID", "FirstName", reservation.UserID);
            }
            //end of diplaying users differently according to a role


            var coursesWithLessons = db.Courses1.Include(c => c.Lessons).Where(c => c.Lessons.Count > 0);

            ViewBag.filter = new SelectList(coursesWithLessons, "CourseID", "CourseName", reservation.Lesson.CourseID);
            ViewBag.LessonID = new SelectList(db.Lessons, "LessonID", "LessonTitle", reservation.LessonID);

            //the value of filter is null when "Edit" is loaded at the first time. the filter value is selected lessons showed are changed according to the selected course.
            if (filter != null)
            {
                var lessons = db.Lessons.Where(l => l.CourseID == filter);
                if (lessons == null) //no need any more because courses in the select list are courses with lessons.
                {
                    ViewBag.LessonID = null;
                }
                else
                {
                    ViewBag.LessonID = new SelectList(lessons, "LessonID", "LessonTitle", reservation.LessonID);

                }
            }

            return View(reservation);
        }


        // POST: Reservations/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ReservationID,ReservationDate,UserID,LessonID")] Reservation reservation)
        {
            if (ModelState.IsValid)
            {
                db.Entry(reservation).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.UserID = new SelectList(db.UserDetails, "UserID", "FirstName", reservation.UserID);
            ViewBag.LessonID = new SelectList(db.Lessons, "LessonID", "LessonTitle", reservation.LessonID);
            return View(reservation);
        }


        // GET: Reservations/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Reservation reservation = db.Reservations.Find(id);
            if (reservation == null)
            {
                return HttpNotFound();
            }
            return View(reservation);
        }


        // POST: Reservations/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Reservation reservation = db.Reservations.Find(id);
            db.Reservations.Remove(reservation);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

FamilySite.UI.MVC/Views/Reservations/Create.cshtml
@model FamilySite.DATA.EF.Reservation

@{
    ViewBag.Title = "Add New Reservation";
}
<div id="family-wrapper">
    <h3>@ViewBag.Title</h3>
    <hr />

    <div class="form-horizontal">
        <div class="form-group">

            @Html.LabelFor(model => model.Lesson.CourseID, "Course", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @using (Html.BeginForm("Create", "Reservations", FormMethod.Get))
            {
                    @* hjkang: if lessonId is trasfered from lesson reserve, it's course will be set as default  *@

                    @Html.DropDownList("filter", null, new { onchange = "this.form.submit();" })
                    @Html.ValidationMessageFor(model => model.Lesson.CourseID, "", new { @class = "text-danger" })

                }
            </div>
        </div>
    </div>

    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <div class="form-horizontal">

            @Html.ValidationSummary(true, "", new { @class = "text-danger" })

            <div class="form-group">
                @Html.LabelFor(model => model.LessonID, "Lesson", htmlAttributes: new { @class = "control-label col-md-2" })


                <div class="col-md-10">
                    @* hjkang: if lessonId is trasfered from lesson reserve, it will be set as default  *@

                    @Html.DropDownList("LessonID", null, htmlAttributes: new { @class = "form-control" })
                    @Html.ValidationMessageFor(model => model.LessonID, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.ReservationDate, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.ReservationDate, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.ReservationDate, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.UserID, "User", htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.DropDownList("UserID", null, htmlAttributes: new { @class = "form-control" })
                    @Html.ValidationMessageFor(model => model.UserID, "", new { @class = "text-danger" })
                </div>
            </div>

            @*<div class="form-group">
                @Html.LabelFor(model => model.Lesson.CourseID, "Course", htmlAttributes: new { @class = "control-label col-md-2" })

                <div class="col-md-10">*@
            @* hjkang: if lessonId is trasfered from reservation, it's course will be set as default  *@

            @*@Html.DropDownList("CourseID", null, htmlAttributes: new { @class = "form-control" })
                            @Html.ValidationMessageFor(model => model.Lesson.CourseID, "", new { @class = "text-danger" })
                        </div>
                </div>*@



            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="Reserve" class="btn btn-primary" />|
                    @Html.ActionLink("Cancel", "Index", null, new { @class = "btn btn-danger" })
                </div>
            </div>
        </div>
    }
</div>

    @section Scripts {
        @Scripts.Render("~/bundles/jqueryval")
    }

FamilySite.UI.MVC/Views/Reservations/Delete.cshtml
@model FamilySite.DATA.EF.Reservation

@{
    ViewBag.Title = "Delete Reservaton on " + Model.ReservationDate.ToShortDateString();
}
<div id="family-wrapper">
<h2>@ViewBag.Title</h2>
<hr />

<h3>Are you sure you want to delete this?</h3>
<div>

    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.ReservationDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ReservationDate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.UserDetail.FirstName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.UserDetail.FirstName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Lesson.LessonTitle)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Lesson.LessonTitle)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-primary" />|
            @Html.ActionLink("No", "Index", null, new { @class = "btn btn-danger" })
        </div>
    }
</div>
</div>

FamilySite.UI.MVC/Views/Reservations/Details.cshtml
@model FamilySite.DATA.EF.Reservation

@{
    ViewBag.Title = "Reservation Details on " + Model.ReservationDate.ToShortDateString();
}
<div id="family-wrapper">
    <h3>@ViewBag.Title</h3>
    <hr />

    <div>
        <dl class="dl-horizontal">
            <dt>
                @Html.DisplayNameFor(model => model.ReservationDate)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.ReservationDate)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.UserDetail.FirstName)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.UserDetail.FirstName)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.Lesson.LessonTitle)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Lesson.LessonTitle)
            </dd>
            <dt>
                @Html.DisplayNameFor(model => model.Lesson.Cours.CourseName)
            </dt>
            <dd>
                @Html.DisplayFor(model => model.Lesson.Cours.CourseName)

            </dd>

        </dl>
    </div>
    <div>
        @Html.ActionLink("Edit", "Edit", new { id = Model.ReservationID }) |
        @Html.ActionLink("Back to List", "Index")
    </div>
</div>

FamilySite.UI.MVC/Views/Reservations/Edit.cshtml
@model FamilySite.DATA.EF.Reservation

@{
    ViewBag.Title = "Edit Reservation on " + Model.ReservationDate.ToShortDateString();
}
<div id="family-wrapper">
    <h3>@ViewBag.Title</h3>
    <hr />

    <div class="form-horizontal">
        <div class="form-group">

            @Html.LabelFor(model => model.Lesson.CourseID, "Course", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @using (Html.BeginForm("Edit", "Reservations", FormMethod.Get))
            {
                    @* hjkang: if lessonId is trasfered from reservation, it's course will be set as default  *@

                    @Html.DropDownList("filter", null, new { onchange = "this.form.submit();" })
                    @Html.ValidationMessageFor(model => model.Lesson.CourseID, "", new { @class = "text-danger" })

                }
            </div>
        </div>
    </div>



    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <div class="form-horizontal">

            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            @Html.HiddenFor(model => model.ReservationID)

            <div class="form-group">
                @Html.LabelFor(model => model.LessonID, "Lesson", htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.DropDownList("LessonID", null, htmlAttributes: new { @class = "form-control" })
                    @Html.ValidationMessageFor(model => model.LessonID, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.ReservationDate, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.ReservationDate, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.ReservationDate, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.UserID, "User", htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.DropDownList("UserID", null, htmlAttributes: new { @class = "form-control" })
                    @Html.ValidationMessageFor(model => model.UserID, "", new { @class = "text-danger" })
                </div>
            </div>



            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="Save" class="btn btn-primary" />|
                    @Html.ActionLink("Cancel", "Index", null, new { @class = "btn btn-danger" })
                </div>
            </div>
        </div>
    }
</div>

    @section Scripts {
        @Scripts.Render("~/bundles/jqueryval")
    }

FamilySite.UI.MVC/Views/Reservations/Index.cshtml
@model IEnumerable<FamilySite.DATA.EF.Reservation>

@{
    ViewBag.Title = "Reservations";
}
<div id="family-wrapper">
<h3>@ViewBag.Title</h3>

<p>
    @Html.ActionLink("Create New Reservation", "Create")
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.ReservationDate)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.UserDetail.FirstName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Lesson.LessonTitle)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.ActionLink(item.ReservationDate.ToShortDateString(), "Details", new { id = item.ReservationID })
                    @*@Html.DisplayFor(modelItem => item.ReservationDate)*@
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.UserDetail.FirstName)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Lesson.LessonTitle)
                </td>
                <td>
                    @Html.ActionLink("Edit", "Edit", new { id = item.ReservationID }) |
                    @*@Html.ActionLink("Details", "Details", new { id=item.ReservationID }) |*@
                    @Html.ActionLink("Delete", "Delete", new { id = item.ReservationID })
                </td>
            </tr>
        }
    </tbody>
</table>
</div>